# Generated by Django 3.2 on 2022-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Instagram_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
