# Generated by Django 3.2 on 2022-12-04 16:05

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Article Category',
            },
        ),
        migrations.CreateModel(
            name='Article_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('Author', models.CharField(default='Admin', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Article_images/')),
                ('Short_Description', models.TextField(blank=True, default='', null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 4, 22, 5, 53, 498962))),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article_category')),
            ],
            options={
                'verbose_name_plural': 'Article Table',
            },
        ),
    ]
