# Generated by Django 3.2 on 2022-12-05 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='Read_Time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 21, 53, 29, 410526)),
        ),
    ]
