# Generated by Django 3.2 on 2022-12-07 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20221205_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 7, 18, 27, 47, 218202)),
        ),
    ]
