# Generated by Django 3.2 on 2022-12-07 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20221207_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 7, 19, 41, 10, 88259)),
        ),
    ]
