# Generated by Django 3.2 on 2022-12-07 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 7, 20, 51, 52, 369954)),
        ),
    ]
