# Generated by Django 3.2 on 2022-12-08 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_article_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 16, 50, 45, 672712)),
        ),
    ]
