# Generated by Django 3.2 on 2022-12-08 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_followers'),
        ('article', '0010_alter_article_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 23, 35, 20, 278684)),
        ),
        migrations.CreateModel(
            name='article_chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('name', models.CharField(max_length=255)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'verbose_name_plural': 'Article Chapter',
            },
        ),
        migrations.AddField(
            model_name='article_table',
            name='Chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article_chapter'),
        ),
    ]
