# Generated by Django 3.2 on 2022-12-10 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_followers'),
        ('article', '0011_auto_20221208_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 11, 12, 18, 660849)),
        ),
        migrations.CreateModel(
            name='article_subchapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('name', models.CharField(max_length=255)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article_chapter')),
            ],
            options={
                'verbose_name_plural': 'Article SubChapter',
            },
        ),
        migrations.AddField(
            model_name='article_table',
            name='Subchapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article_subchapter'),
        ),
    ]
