# Generated by Django 3.2 on 2022-12-11 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_article_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 15, 19, 30, 187678)),
        ),
        migrations.CreateModel(
            name='track_views',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField(blank=True, default=1, null=True)),
                ('device_os', models.CharField(blank=True, max_length=200, null=True)),
                ('device_browser', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(blank=True, max_length=200, null=True)),
                ('device_model', models.CharField(blank=True, max_length=200, null=True)),
                ('site_url', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('location_longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('location_latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('location_country', models.CharField(blank=True, max_length=200, null=True)),
                ('location_region', models.CharField(blank=True, max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, max_length=200, null=True)),
                ('location_zip', models.CharField(blank=True, max_length=200, null=True)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article_table')),
            ],
            options={
                'verbose_name_plural': 'Track Views',
            },
        ),
    ]
