# Generated by Django 3.2 on 2022-12-11 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20221211_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track_views',
            old_name='device_id',
            new_name='user_uid',
        ),
        migrations.RemoveField(
            model_name='track_views',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 15, 28, 54, 809387)),
        ),
    ]
