# Generated by Django 3.2 on 2022-12-11 15:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0016_auto_20221211_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 21, 7, 47, 125111)),
        ),
        migrations.CreateModel(
            name='search_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('search_word', models.CharField(blank=True, max_length=255, null=True)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 21, 7, 47, 130946))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Logs',
            },
        ),
    ]
